name: Pull Request

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install distro packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt-get -y install libboost-dev zlib1g-dev libgtest-dev libeigen3-dev libzstd-dev ninja-build meson
    - uses: actions/checkout@v2
    - name: meson setup
      run: meson setup builddir
    - name: ninja build
      run: ninja -C builddir
    - name: ninja build unittests
      run: ninja -C builddir unittests
    - name: run unittests
      run: |
        ./builddir/unittests

